{"name": "test_try_and_log_with_qbet_user", "status": "broken", "statusDetails": {"message": "pytest_bdd.exceptions.StepDefinitionNotFoundError: Step definition is not found: Given \"I go to the login menu I try to login with Qbet user.\". Line 12 in scenario \"Try and log with Qbet user\" in the feature \"/Users/razvan/Work/qa_qreen_web/web_tests/features/login.feature\"", "trace": "feature = Feature(scenarios=OrderedDict([('Register new user and then log in with the newly created user', ScenarioTemplate(feat...e', name='Login tests for users', tags=set(), background=None, line_number=1, description='Tests for logging in users')\nscenario = Scenario(feature=Feature(scenarios=OrderedDict([('Register new user and then log in with the newly created user', Scen... keyword='And', failed=False, scenario=..., background=None, lines=[]), ...]), background=None, lines=[])], tags=set())\nrequest = <FixtureRequest for <Function test_try_and_log_with_qbet_user>>\n\n    def _execute_scenario(feature: Feature, scenario: Scenario, request: FixtureRequest) -> None:\n        \"\"\"Execute the scenario.\n    \n        :param feature: Feature.\n        :param scenario: Scenario.\n        :param request: request.\n        :param encoding: Encoding.\n        \"\"\"\n        __tracebackhide__ = True\n        request.config.hook.pytest_bdd_before_scenario(request=request, feature=feature, scenario=scenario)\n    \n        try:\n            for step in scenario.steps:\n                step_func_context = get_step_function(request=request, step=step)\n                if step_func_context is None:\n                    exc = exceptions.StepDefinitionNotFoundError(\n                        f\"Step definition is not found: {step}. \"\n                        f'Line {step.line_number} in scenario \"{scenario.name}\" in the feature \"{scenario.feature.filename}\"'\n                    )\n                    request.config.hook.pytest_bdd_step_func_lookup_error(\n                        request=request, feature=feature, scenario=scenario, step=step, exception=exc\n                    )\n>                   raise exc\nE                   pytest_bdd.exceptions.StepDefinitionNotFoundError: Step definition is not found: Given \"I go to the login menu I try to login with Qbet user.\". Line 12 in scenario \"Try and log with Qbet user\" in the feature \"/Users/razvan/Work/qa_qreen_web/web_tests/features/login.feature\"\n\n/opt/anaconda3/lib/python3.9/site-packages/pytest_bdd/scenario.py:192: StepDefinitionNotFoundError"}, "description": "/Users/razvan/Work/qa_qreen_web/web_tests/features/login.feature: Try and log with Qbet user", "steps": [{"name": "User is not logged in.", "status": "passed", "steps": [{"name": "Checking if user is not logged in.", "status": "passed", "steps": [{"name": "Assert Message equals.", "status": "passed", "parameters": [{"name": "actual", "value": "True"}, {"name": "expected", "value": "True"}], "start": 1674520021754, "stop": 1674520021754}], "start": 1674520020561, "stop": 1674520021754}], "parameters": [{"name": "pages", "value": "{'about_page': <pages.about_page.AboutPage object at 0x1073a6c70>, 'login_page': <pages.login_page.LoginPage object at 0x1073a6ac0>, 'registration_page': <pages.registration_page.RegistrationPage object at 0x1073a6dc0>}"}], "start": 1674520020561, "stop": 1674520021754}], "attachments": [{"name": "log", "source": "ddda9b0a-1c37-42e3-b102-cdaf025527dd-attachment.txt", "type": "text/plain"}], "start": 1674520020561, "stop": 1674520021754, "uuid": "0507359f-315c-4285-b52b-97d4fd1da343", "historyId": "6d8c639fb10f0b965038cb3d3a3dd50b", "testCaseId": "7cb9ef65e44c87294e0f643d123231e8", "fullName": "test_user_login#test_try_and_log_with_qbet_user", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures"}, {"name": "suite", "value": "test_user_login"}, {"name": "host", "value": "Razvans-MacBook-Pro.local"}, {"name": "thread", "value": "33473-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_user_login"}]}